BEGIN;

DELETE FROM HIST_COMPONENTES_COMPOSICAO ;

DELETE FROM HIST_COMPOSICAO ;

INSERT
  INTO HIST_COMPOSICAO (HIST_COMP_ID, HIST_COMP_PROCOD, HIST_COMP_TIPO, HIST_COMP_OFERTA,
                        HIST_COMP_COMPOSICAO, HIST_COMP_QUANTIDADE, HIST_COMP_BAIXA, HIST_COMP_DATA)
SELECT COMP_ID
     , COMP_PROCOD
     , COMP_TIPO
     , COMP_OFERTA
     , COMP_COMPOSICAO
     , COMP_QUANTIDADE
     , COMP_BAIXA
     , TO_DATE('01/01/2017','DD/MM/YYYY')
  FROM COMPOSICAO
;

INSERT
  INTO HIST_COMPONENTES_COMPOSICAO (HIST_CC_ID, HIST_CC_PROCOD, HIST_CC_QUANTIDADE,
                                    HIST_CC_PRECO1, HIST_CC_PRECO2, HIST_CC_PRECO3, HIST_CC_COMP_ID)
SELECT CC_ID
     , CC_PROCOD
     , CC_QUANTIDADE
     , CC_PRECO1
     , CC_PRECO2
     , CC_PRECO3
     , CC_COMP_ID
  FROM COMPONENTES_COMPOSICAO
;

UPDATE HIST_COMPONENTES_COMPOSICAO
   SET HIST_COD_HIST_COMP_ID = (SELECT MAX(HC.HIST_COMP_ID) FROM HIST_COMPOSICAO HC WHERE HC.HIST_COMP_PROCOD = HIST_CC_PROCOD)
 WHERE HIST_CC_PROCOD IN (SELECT PROCOD FROM PRODUTO WHERE PROCOMP = 'C')
;

UPDATE ITEM_VENDA
   SET HIST_COMP_ID = C.HIST_COMP_ID
  FROM (SELECT HIST_COMP_PROCOD,HIST_COMP_ID FROM HIST_COMPOSICAO) AS C
 WHERE PROCOD = C.HIST_COMP_PROCOD
;

UPDATE ITEM_NOTA_FISCAL
   SET HIST_COMP_ID = C.HIST_COMP_ID
  FROM (SELECT HIST_COMP_PROCOD,HIST_COMP_ID FROM HIST_COMPOSICAO) AS C
 WHERE PROCOD = C.HIST_COMP_PROCOD
;

SELECT SETVAL('SQ_COMPOSICAO_HIST',(SELECT MAX(HIST_COMP_ID)+1 FROM HIST_COMPOSICAO), FALSE);
SELECT SETVAL('SQ_COMP_COMPOSICAO_HIST',(SELECT MAX(HIST_COMP_ID)+1 FROM HIST_COMPOSICAO), FALSE);