--ALTERAR O CNPJ

DELETE FROM FILA_SINCRONIZACAO;
DELETE FROM FILA_SINCRONIZACAO_PANAMA;
UPDATE PESSOA SET PES_NUM_DOCUMENTO = '70177837000196' WHERE PES_CODIGO = 61;
UPDATE USUARIO SET USUSEN = MD5('admin') WHERE FUNCOD = 1;
UPDATE USUARIO SET ATIVO = 'false' WHERE FUNCOD > 1;