DO language plpgsql $$
DECLARE
        L BIGINT;
        C VARCHAR(3);
        D DATE;
        S VARCHAR(6);
begin
        L := 1;
        C := '005';
        D := '2017-10-02';
        S := '274661';

        raise notice '% - Processo iniciado.', timeofday()::timestamp;

        INSERT INTO FILA_SINCRONIZACAO_PANAMA (ID, IDENTIFICADOR, PRIORIDADE, ENTIDADE_ID, OPERACAO)
                    (SELECT NEXTVAL('SQ_FILA_SINCRONIZACAO_PANAMA'), 'VENDA', 2, VENDA.id, 'EXCLUSAO'
                    FROM (SELECT T.TRNSEQ::TEXT||'-'||T.CXANUM::TEXT||'-'||T.LOJCOD::TEXT||'-'||TO_CHAR(T.TRNDAT, 'yyyy-MM-dd') AS "id"
                        FROM TRANSACAO T
                        WHERE T.TRNTIP IN ('1','7') AND T.LOJCOD = L AND T.CXANUM = C AND T.TRNDAT = D AND TRNSEQ = S )
                    VENDA);

        DELETE FROM REDUCAO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM ESTATISTICA_PRODUTO_VENDA WHERE EPV_LOJCOD = L AND EPV_CXANUM = C AND EPV_TRNSEQ = S;
        DELETE FROM ESTOQUE_MOVIMENTACAO WHERE MOV_ID IN (
                SELECT
                        MOV_ID
                FROM
                        ESTOQUE_MOVIMENTACAO
                WHERE
                        MOV_TIPO='VENDA' AND
                        LOJ_CODIGO = L AND
                        MOV_DATA = D AND
                        SUBSTRING(MOV_HISTORICO, 7) = S || '/' || C
        );
        DELETE FROM TRANSACAO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM ITEM_VENDA WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM FINALIZACAO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM TRANSACAOITEMTEFDLL WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM TRANSACAOTEFDLL WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM ITEM_RECEBIMENTO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM ITEM_PAGAMENTO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM ITEM_PLANO_PAGAMENTO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM PREVENDA WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM TROCA_FINALIZACAO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM OCORRENCIA_PDV WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM SANGRIA_CONCILIACAO WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;
        DELETE FROM TRANSACAO_XMLNOTA WHERE LOJCOD = L AND CXANUM = C AND TRNDAT = D AND TRNSEQ = S;

        raise notice '% - Processo concluido.', timeofday()::timestamp;
end
$$;