DO language plpgsql $$
DECLARE
        L BIGINT;
        C VARCHAR(3);
        D DATE;
begin
        L := 1;
        D := '2017-09-04';

        RAISE NOTICE '% - PROCESSO INICIADO.', timeofday()::timestamp;

        INSERT INTO FILA_SINCRONIZACAO_PANAMA (ID, IDENTIFICADOR, PRIORIDADE, ENTIDADE_ID, OPERACAO)
            (SELECT NEXTVAL('SQ_FILA_SINCRONIZACAO_PANAMA'), 'VENDA', 2, VENDA.id, 'EXCLUSAO'
            FROM (SELECT T.TRNSEQ::TEXT||'-'||T.CXANUM::TEXT||'-'||T.LOJCOD::TEXT||'-'||TO_CHAR(T.TRNDAT, 'yyyy-MM-dd') AS "id"
                FROM TRANSACAO T
                WHERE T.TRNTIP IN ('1','7') AND T.LOJCOD = L AND T.TRNDAT = D )
            VENDA);
	
	DELETE FROM REDUCAO WHERE LOJCOD = L AND TRNDAT = D;
	DELETE FROM ESTATISTICA_PRODUTO_VENDA WHERE EPV_DATA_VENDA = D AND EPV_LOJCOD = L;
        DELETE FROM ESTOQUE_MOVIMENTACAO WHERE MOV_ID IN (
                SELECT
                        MOV_ID
                FROM
                        ESTOQUE_MOVIMENTACAO
                WHERE
                        LOJ_CODIGO = L AND
                        MOV_DATA = D AND
                        (MOV_TIPO='VENDA' OR MOV_TIPO='CANCELAMENTO')
        );

        DELETE FROM TRANSACAO WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM ITEM_VENDA WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM FINALIZACAO WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM TRANSACAOITEMTEFDLL WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM TRANSACAOTEFDLL WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM ITEM_RECEBIMENTO WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM ITEM_PAGAMENTO WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM ITEM_PLANO_PAGAMENTO WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM PREVENDA WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM OCORRENCIA_PDV WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM SANGRIA_CONCILIACAO WHERE LOJCOD = L AND TRNDAT = D;
        DELETE FROM TRANSACAO_XMLNOTA WHERE LOJCOD = L AND TRNDAT = D;
	
        RAISE NOTICE '% - PROCESSO CONCLUIDO.', timeofday()::timestamp;
end
$$;